### ISSUE TITLE
Generating a project misses .mvn folders

### ISSUE THREAD

**Issue by TimvdLippe** [metaborg/spoofax-intellij#18]
Generation of a project probably misses the `.mvn` folders and thus does not build

### I tried to do this:

1. Generate a project
2. Run `mvn install`

### I expected this to happen:

Build succeeds

### Instead, this happened:

Build fails with missing configuration.

---

> Spoofax: <plugin version>

**Comment by Virtlink** [comment]
And it does work with a project generated from Eclipse?

Can you provide the exact error?

**Comment by TimvdLippe** [comment]
Hm, for some reason I can not reproduce. Maybe it was related to Intellij 2016.3 vs 2017.1? I am running your local version now and there it does work at least...

**Comment by Virtlink** [comment]
Ok, thanks. That's a possibility, maybe the older IntelliJ generated an older project structure that no longer works.
