### ISSUE TITLE
Plugin doesn't install with 2017.2.5

### ISSUE THREAD

**Issue by cbruegg** [metaborg/spoofax-intellij#21]
When installing the plugin from the repository, it downloads the plugin but then fails without an error when the download is finished. I've manually downloaded the ZIP file containing the plugin and tried to install it manually, but when I try to install it, it says "Plugin 'Spoofax' is incompatible with this installation."

> Spoofax: Revision 88bb46e (current `master`)

**Comment by Virtlink** [comment]
Apparently the repository didn't get updated for a while, so it serves an old version of the plugin that's incompatible with the more recent IntelliJ installations. You can try one of the other suggestions in the [Quick Start](https://github.com/metaborg/spoofax-intellij#quick-start) for installing Spoofax in IntelliJ; or use Spoofax [with Eclipse](http://www.metaborg.org/en/latest/source/install.html) as that version is more maintained and mature, and currently gives a better developer experience.
