### ISSUE TITLE
Build failed with an exception - Could not find io.usethesource:capsule:0.6.1.

### ISSUE THREAD

**Issue by diederikd** [metaborg/spoofax-intellij#24]
<short summary of the issue>

./gradlew runide

gives:

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':org.metaborg.spoofax-deps:runtimeClasspath'.
> Could not find io.usethesource:capsule:0.6.1.
  Required by:
      project :org.metaborg.spoofax-deps > org.metaborg:org.metaborg.spoofax.core:2.5.0-SNAPSHOT > org.metaborg:nabl2.solver:2.5.0-SNAPSHOT
      project :org.metaborg.spoofax-deps > org.metaborg:org.metaborg.spoofax.core:2.5.0-SNAPSHOT > org.metaborg:flowspec.runtime:2.5.0-SNAPSHOT
      project :org.metaborg.spoofax-deps > org.metaborg:org.metaborg.spoofax.core:2.5.0-SNAPSHOT > org.metaborg:nabl2.solver:2.5.0-SNAPSHOT > org.metaborg:nabl2.terms:2.5.0-SNAPSHOT

I will deliver a fix.

**Comment by Virtlink** [comment]
Thank you for your bug report and pull request! I'm not sure why we hadn't caught this issue on our build server.
