### ISSUE TITLE
"(language-name) > syntax > Show parsed AST" works even with malformed input

### ISSUE THREAD

**Issue by qwaz** [metaborg/spoofax-intellij#27]
Using the menu to parse `vertex.has(123)` creates `.aterm` file with [this AST](https://pastebin.com/raw/My9abNh8). This is an invalid expression in my language and should be rejected.

I thought my language definition was wrong, but `parseUnit.success()` was correctly returning `false`. It seems that the plugin only checks for `parseUnit.valid()` when generating `.aterm` file.

### I tried to do this:

Use "(language-name) > syntax > Show parsed AST" option with malformed input.

### I expected this to happen:

It fails, or shows intermediate result with warning or alert which indicates that the actual parsing was failed.

### Instead, this happened:

The plugin shows intermediate result without any warning or error.

---

> Spoofax: 2.4.1

**Comment by qwaz** [comment]
It actually looks like an issue of Spoofax itself. I just found that all editor actions are defined in language itself with `.esv` format. Should I move this issue to Spoofax issue tracker?

**Comment by Virtlink** [comment]
Thanks for the bug report! Yes, I think it would be better to move it to the Spoofax issue tracker [on Yellowgrass](http://yellowgrass.org/project/Spoofax).

**Comment by Virtlink** [comment]
I just verified this is indeed also an issue in Spoofax for Eclipse.
