### ISSUE TITLE
Cannot build initial project

### ISSUE THREAD

**Issue by Gohla** [metaborg/spoofax-intellij#5]
Generating a new initial project and building it fails.

I tried to do this:

Create an initial project (called 'test') and build it by right clicking the project and choosing "Build module 'test'"

I expected this to happen:

Building to succeed.

Instead, this happened:

Building fails with the following error:

```
Information:21/12/2016, 16:47 - Compilation completed with 1 error and 0 warnings in 7s 936ms
Error:Missing language dependency: Language for dependency org.metaborg:org.metaborg.meta.lang.esv:2.1.0-SNAPSHOT does not exist
```

---

Latest master at this time.

**Comment by Virtlink** [comment]
Known issue, but I thought it was an error outside my control since Jeff [reported it](https://slde.slack.com/archives/spoofax/p1480431388000147) as a Maven error as well.

**Comment by Gohla** [comment]
That error is triggered if you have a dependency on ESV in metaborg.yaml, but that language is not loaded into Spoofax Core. Jeff probably got it because he uses a custom POM file for his Scala stuff, but forgot to add a dependency to ESV in the POM file.

I understand that building works separately from the IDE as a JPS plugin, does this plugin have all those languages loaded?

**Comment by Virtlink** [comment]
Okay, thanks for the pointer. It should have these languages loaded by default:

```
org.metaborg:org.metaborg.meta.lang.analysis:2.1.0-SNAPSHOT
org.metaborg:org.metaborg.meta.lang.esv:2.1.0-SNAPSHOT
org.metaborg:org.metaborg.meta.lang.nabl:2.1.0-SNAPSHOT
org.metaborg:org.metaborg.meta.lang.sdf:2.1.0-SNAPSHOT
org.metaborg:org.metaborg.meta.lang.stratego:2.1.0-SNAPSHOT
org.metaborg:org.metaborg.meta.lang.template:2.1.0-SNAPSHOT
org.metaborg:org.metaborg.meta.lang.ts:2.1.0-SNAPSHOT
org.metaborg:org.metaborg.meta.lib.analysis:2.1.0-SNAPSHOT
```
